name: build this branch

on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x'

#    - name: install vs code
#      run: |
        # Install necessary components for building ASP.NET projects
#        choco install visualstudio2019-workload-netweb --version=16.11.31829.152

    - name: restore dependencies
      run: dotnet restore

    - name: build
      run: dotnet build --configuration Release --no-restore
