name: build this branch

on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x'

    - name: restore dependencies
      run: dotnet restore

    - name: build
      run: dotnet build --configuration Release --no-restore
